on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t ghcr.io/kordianpawelec/dashboard:latest .
      
      - name: push docker image
        run: docker push ghcr.io/kordianpawelec/dashboard:latest

deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to vsp
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_HOST }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/dev/dashboard
          git pull origin main
          docker pull ghcr.io/kordianpawelec/dashboard:latest
          docker compose down
          docker compose up -d